# See config.example.yml for documentation.
object_base: orig/R9IE01
object: sys/main.dol
hash: 551306334183a633d0fde434a930b98809433b70
symbols: config/R9IE01/symbols.txt
splits: config/R9IE01/splits.txt
common_start: 0x80490e18
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 14

